# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Download qnap source code
          wget https://liquidtelecom.dl.sourceforge.net/project/qosgpl/QNAP%20NAS%20GPL%20Source/QTS%204.5.3/GPL_QTS-4.5.3-20210602_Kernel.tar.gz -O ~/GPL_QTS-4.5.3-20210602_Kernel.tar.gz
          mkdir ~/GPL_QTS && tar -xzvf GPL_QTS-4.5.3-20210602_Kernel.tar.gz -C GPL_QTS
          cd ~/GPL_QTS
