# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Build driver
        run: |
          echo Download qnap kernel code
          mkdir QTS
          wget https://liquidtelecom.dl.sourceforge.net/project/qosgpl/QNAP%20NAS%20GPL%20Source/QTS%204.5.3/GPL_QTS-4.5.3-20210602_Kernel.tar.gz -O QTS/GPL_QTS-4.5.3-20210602_Kernel.tar.gz
          cd QTS && tar -xzvf GPL_QTS-4.5.3-20210602_Kernel.tar.gz
          cd GPL_QTS/src/linux-4.14
          make modules SUBDIRS=drivers/hwmon/
          echo Build complete!

      - name: Archive driver
        uses: actions/upload-artifact@v2
        with:
          name: it87-driver
          path: QTS/GPL_QTS/src/linux-4.14/drivers/hwmon/it87.ko

